export const COUNTRIES = [
  "United States",
  "Canada",
  "India",
  "United Kingdom",
  "Australia",
  "Germany",
  "France",
  "Japan",
  "Brazil",
  "China",
  "Italy",
  "Mexico",
  "South Korea",
  "Spain",
  "Russia",
  "Saudi Arabia",
  "South Africa",
  "Egypt",
  "Thailand",
  "Argentina",
];
export const INDUSTRIES = [
  "Digital Marketing",
  "Technology",
  "Healthcare",
  "Finance",
  "Education",
  "Entertainment",
  "Retail",
  "Manufacturing",
  "Construction",
  "Real Estate",
  "Transportation",
  "Telecommunications",
  "Hospitality",
  "Energy",
  "Agriculture",
  "Automotive",
  "Aerospace",
  "Pharmaceuticals",
  "Tourism",
  "Insurance",
  "Food & Beverage",
];

export const DEFAULT_KEYWORDS =
  "digital marketing, SEO, PPC, social media marketing, content marketing, Google Ads, Facebook Ads, Instagram Reels, online advertising, website traffic, email marketing, affiliate marketing, branding, lead generation, conversion optimization, retargeting ads, keyword research, website analytics, Google Analytics, ad copywriting, blogging tips, web design, UX/UI design, search engine ranking, mobile marketing, social media strategy, video marketing, content strategy, programmatic advertising, artificial intelligence";
